In [1]:
#sort,searching and counting function

In [2]:
import numpy as np

In [12]:
ar=np.array([2,334,56,23,75,1,2,3,4])

In [13]:
ar

array([  2, 334,  56,  23,  75,   1,   2,   3,   4])

In [14]:
np.sort(ar)

array([  1,   2,   2,   3,   4,  23,  56,  75, 334])

In [15]:
np.searchsorted(ar,76)

9

In [19]:
ar1=np.array([9,7,5,6,34,2,9,0,0,0,0])

In [20]:
ar1

array([ 9,  7,  5,  6, 34,  2,  9,  0,  0,  0,  0])

In [21]:
np.count_nonzero(ar1)

7

In [22]:
ar

array([  2, 334,  56,  23,  75,   1,   2,   3,   4])

In [25]:
np.where(ar>6) # provide index

(array([1, 2, 3, 4]),)

In [27]:
np.extract(ar>6,ar)

array([334,  56,  23,  75])

In [28]:
ar.byteswap()

array([ 144115188075855872, 5620773809935089664, 4035225266123964416,
       1657324662872342528, 5404319552844595200,   72057594037927936,
        144115188075855872,  216172782113783808,  288230376151711744])

In [29]:
#numpy- copies and views

In [30]:
ar

array([  2, 334,  56,  23,  75,   1,   2,   3,   4])

In [33]:
a=np.copy(ar) #deep copy

In [34]:
a

array([  2, 334,  56,  23,  75,   1,   2,   3,   4])

In [35]:
b=ar.view()

In [ ]:
b=ar # swalow copy

In [36]:
b

array([  2, 334,  56,  23,  75,   1,   2,   3,   4])

In [37]:
ar

array([  2, 334,  56,  23,  75,   1,   2,   3,   4])

In [41]:
b[0]=34 # swalow copy

In [42]:
b

array([ 34, 334,  56,  23,  75,   1,   2,   3,   4])

In [43]:
ar

array([ 34, 334,  56,  23,  75,   1,   2,   3,   4])

In [44]:
 #numpy matrixes

In [45]:
import numpy.matlib as nm

In [46]:
nm.zeros(4)

matrix([[0., 0., 0., 0.]])

In [47]:
nm.ones((4,6))

matrix([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [49]:
#identity matrix
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [50]:
#numpy linear algebra

In [57]:
ar1=np.array([[2,3],[4,5]])
ar2=np.array([[5,3],[2,5]])

In [58]:
ar1

array([[2, 3],
       [4, 5]])

In [59]:
ar2

array([[5, 3],
       [2, 5]])

In [60]:
np.dot(ar1,ar2)

array([[16, 21],
       [30, 37]])

In [62]:
ar1@ar2

array([[16, 21],
       [30, 37]])