In [186]:
import numpy as np
import logging
logging.basicConfig(filename="num.log",level=logging.DEBUG,format="%(asctime)s %(name)s %(levelname)s %(message)s")

In [187]:
l=[1,2,4,5]
logging.info("this is one dimensional array")
logging.info("array is the super class of numpy")
np.array(l)

array([1, 2, 4, 5])

In [188]:
l1=[[5,34,6,4],
   [7,4,85,4]]
logging.info("this is two dimensional array")
a=np.array(l1)

In [189]:
a

array([[ 5, 34,  6,  4],
       [ 7,  4, 85,  4]])

In [190]:
logging.info("btoh are generate array")
np.asarray(l1)
np.asanyarray(l1)

array([[ 5, 34,  6,  4],
       [ 7,  4, 85,  4]])

In [5]:
logging.info("this is sub class not change in as asarray becouse is already in array")
np.matrix(l)

matrix([[1, 2, 4, 5]])

In [6]:
b=a

In [7]:
type(b)

numpy.ndarray

In [8]:
logging.info("swallow copy")
b[0][0]=10
b

array([[10, 34,  6,  4],
       [ 7,  4, 85,  4]])

In [9]:
a

array([[10, 34,  6,  4],
       [ 7,  4, 85,  4]])

In [10]:
logging.info("deep copy")
d=np.copy(a)
d[0][2]=234
d

array([[ 10,  34, 234,   4],
       [  7,   4,  85,   4]])

In [11]:
a

array([[10, 34,  6,  4],
       [ 7,  4, 85,  4]])

In [12]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [13]:

np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [14]:
treable=(i*i  for i in range(45))
np.fromiter(treable,int)

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936])

In [15]:
np.fromstring("23 25 26",sep=' ')

array([23., 25., 26.])

In [33]:
#pyhton numpy datatype
l2=[[5,34,6,4],
   [7,4,85,4]]
arr=np.array(l2)
logging.info("dimensional of array")
arr .ndim

2

In [34]:
arr

array([[ 5, 34,  6,  4],
       [ 7,  4, 85,  4]])

In [35]:
logging.info("size of array")
arr.size

8

In [36]:
logging.info("row column")
arr.shape

(2, 4)

In [38]:
arr.dtype

dtype('int64')

In [39]:
arr=np.array([(1,2,3,4),(6,7,85,5)])
arr

array([[ 1,  2,  3,  4],
       [ 6,  7, 85,  5]])

In [191]:
list(range(5))

[0, 1, 2, 3, 4]

In [41]:
list(range(5.1))

TypeError: 'float' object cannot be interpreted as an integer

In [43]:
np.arange(2.4,5.9)

array([2.4, 3.4, 4.4, 5.4])

In [44]:
list(np.arange(2.5,7.5))

[2.5, 3.5, 4.5, 5.5, 6.5]

In [46]:
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [53]:
np.zeros(4)

array([0., 0., 0., 0.])

In [54]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
np.ones(4)

array([1., 1., 1., 1.])

In [58]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
a=np.ones((3,4,4))

In [64]:
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [65]:
a+10

array([[[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]],

       [[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]],

       [[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]]])

In [71]:
np.empty((3,6))

array([[4.64679349e-310, 0.00000000e+000, 6.90551414e-310,
        6.90551388e-310, 6.90551413e-310, 6.90551407e-310],
       [6.90551409e-310, 6.90551294e-310, 6.90551402e-310,
        6.90551404e-310, 6.90551415e-310, 6.90551415e-310],
       [6.90551412e-310, 6.90551412e-310, 6.90551294e-310,
        6.90551416e-310, 6.90551397e-310, 6.90551414e-310]])

In [72]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
np.logspace(2,4,5)

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

In [86]:
rand=np.random.randn(5,3)

In [87]:
import pandas as pd
pd.DataFrame(rand)

0         1         2
0  0.542248  0.791163 -2.154587
1 -0.734485 -0.520260 -2.209515
2  1.130166  2.035379 -0.037545
3  0.499005  0.271698 -0.519635
4  0.345727 -1.247477  0.648981

In [88]:
np.random.rand(3,6)

array([[0.33940142, 0.11879889, 0.17795206, 0.35778115, 0.2376465 ,
        0.04754517],
       [0.88124497, 0.71946968, 0.54459412, 0.91368824, 0.50707695,
        0.37425507],
       [0.33474185, 0.84046955, 0.62933875, 0.80809517, 0.30404687,
        0.15328126]])

In [92]:
arr2=np.random.randint(1,100,(4,4))

In [94]:
arr2

array([[30, 28, 97, 50],
       [36, 10, 24, 87],
       [48, 47, 55, 33],
       [24, 71, 49,  8]])

In [95]:
pd.DataFrame(np.random.randint(1,100,(10,20))).to_csv("rand.csv")

In [99]:
arr3=arr2.reshape(8,2)

In [100]:
arr3

array([[30, 28],
       [97, 50],
       [36, 10],
       [24, 87],
       [48, 47],
       [55, 33],
       [24, 71],
       [49,  8]])

In [102]:
arr3[2:7,1]

array([10, 87, 47, 33, 71])

In [107]:
arr=np.random.randint(1,100,(5,5))
arr[arr>30]

array([51, 36, 80, 74, 49, 91, 64, 45, 65, 67, 84, 87, 74, 89, 80, 78, 49,
       68, 60])

In [108]:
arr

array([[14, 51, 36, 80, 74],
       [49, 91, 64, 45, 65],
       [14, 12, 67, 84, 87],
       [26, 74, 89, 80,  2],
       [78, 19, 49, 68, 60]])

In [121]:
arr[2:4,1:3]

array([[12, 67],
       [74, 89]])

In [122]:
arr[2:4,[1,2]]

array([[12, 67],
       [74, 89]])

In [134]:
arr1=np.random.randint(1,4,(3,3))
arr2=np.random.randint(1,4,(3,3))
arr1

array([[3, 2, 1],
       [2, 3, 1],
       [2, 2, 1]])

In [135]:
arr2

array([[3, 1, 1],
       [2, 1, 1],
       [2, 3, 2]])

In [136]:
arr1+arr2

array([[6, 3, 2],
       [4, 4, 2],
       [4, 5, 3]])

In [137]:
arr1*arr2

array([[9, 2, 1],
       [4, 3, 1],
       [4, 6, 2]])

In [139]:
#first matrix=m*n 
#second matrix=p*q
#condition first matrix column n == second matrix row p
arr1@arr2

array([[15,  8,  7],
       [14,  8,  7],
       [12,  7,  6]])

In [140]:
arr1/0

/tmp/ipykernel_84/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [141]:
arr1**2

array([[9, 4, 1],
       [4, 9, 1],
       [4, 4, 1]])

In [142]:
arr1+100

array([[103, 102, 101],
       [102, 103, 101],
       [102, 102, 101]])

In [169]:
logging.info("numpy in brodcasting")

In [170]:
arr=np.zeros((3,3))

In [171]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [172]:
row=np.array([1,2,3])

In [173]:
row

array([1, 2, 3])

In [174]:
arr+row

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [175]:
row=np.array([[1,2,3]])

In [176]:
row

array([[1, 2, 3]])

In [177]:
row.T

array([[1],
       [2],
       [3]])

In [178]:
arr+row.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [179]:
s=np.random.randint(1,10,(3,3))

In [180]:
s

array([[6, 3, 4],
       [1, 7, 2],
       [8, 2, 8]])

In [181]:
np.sqrt(s)

array([[2.44948974, 1.73205081, 2.        ],
       [1.        , 2.64575131, 1.41421356],
       [2.82842712, 1.41421356, 2.82842712]])

In [184]:
np.log10(s)

array([[0.77815125, 0.47712125, 0.60205999],
       [0.        , 0.84509804, 0.30103   ],
       [0.90308999, 0.30103   , 0.90308999]])