In [3]:
import numpy as np

In [12]:
arr=np.random.randint(1,3,(2,4))

In [13]:
arr

array([[2, 1, 2, 2],
       [2, 1, 2, 2]])

In [15]:
arr.reshape(4,2)

array([[2, 1],
       [2, 2],
       [2, 1],
       [2, 2]])

In [17]:
arr.reshape(2,4)

array([[2, 1, 2, 2],
       [2, 1, 2, 2]])

In [18]:
arr.T

array([[2, 2],
       [1, 1],
       [2, 2],
       [2, 2]])

In [20]:
arr.flatten()

array([2, 1, 2, 2, 2, 1, 2, 2])

In [21]:
arr1=np.array([1,2,3,4,5])

In [22]:
arr1.ndim

1

In [24]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [25]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [26]:
arr

array([[2, 1, 2, 2],
       [2, 1, 2, 2]])

In [27]:
np.squeeze(arr)

array([[2, 1, 2, 2],
       [2, 1, 2, 2]])

In [30]:
dta=np.array([[1],[4],[7],[7]])

In [31]:
dta

array([[1],
       [4],
       [7],
       [7]])

In [32]:
np.squeeze(dta)

array([1, 4, 7, 7])

In [33]:
arr1

array([1, 2, 3, 4, 5])

In [35]:
np.repeat(arr1,6)

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 5, 5, 5, 5, 5, 5])

In [36]:
np.roll(arr1,shift=2) # index me 2+ krega

array([4, 5, 1, 2, 3])

In [37]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [38]:
#numpy - Binary operation

In [39]:
arr2=np.random.randint(1,10,(3,4))
arr3=np.random.randint(1,10,(3,4))

In [40]:
arr2

array([[7, 8, 4, 1],
       [2, 6, 2, 8],
       [9, 5, 1, 9]])

In [41]:
arr3

array([[5, 2, 3, 9],
       [2, 1, 7, 7],
       [7, 7, 5, 4]])

In [42]:
arr2*arr3

array([[49, 64, 16,  1],
       [ 4, 36,  4, 64],
       [81, 25,  1, 81]])

In [43]:
arr2+arr3

array([[12, 10,  7, 10],
       [ 4,  7,  9, 15],
       [16, 12,  6, 13]])

In [44]:
arr2%arr3

array([[2, 0, 1, 1],
       [0, 0, 2, 1],
       [2, 5, 1, 1]])

In [45]:
arr2/arr3

array([[1.4       , 4.        , 1.33333333, 0.11111111],
       [1.        , 6.        , 0.28571429, 1.14285714],
       [1.28571429, 0.71428571, 0.2       , 2.25      ]])

In [46]:
arr2**arr3

array([[  16807,      64,      64,       1],
       [      4,       6,     128, 2097152],
       [4782969,   78125,       1,    6561]])

In [49]:
arr2

array([[7, 8, 4, 1],
       [2, 6, 2, 8],
       [9, 5, 1, 9]])

In [50]:
arr3

array([[5, 2, 3, 9],
       [2, 1, 7, 7],
       [7, 7, 5, 4]])

In [48]:
arr2 & arr3

array([[5, 0, 0, 1],
       [2, 0, 2, 0],
       [1, 5, 1, 0]])

In [51]:
arr2 | arr3

array([[ 7, 10,  7,  9],
       [ 2,  7,  7, 15],
       [15,  7,  5, 13]])

In [53]:
-arr2

array([[-7, -8, -4, -1],
       [-2, -6, -2, -8],
       [-9, -5, -1, -9]])

In [52]:
arr2 > arr3

array([[ True,  True,  True, False],
       [False,  True, False,  True],
       [ True, False, False,  True]])

In [54]:
#numpy in string function

In [56]:
arr=np.array(["yashh","pancharya"])

In [57]:
arr

array(['yashh', 'pancharya'], dtype='<U9')

In [58]:
np.char.upper(arr)

array(['YASHH', 'PANCHARYA'], dtype='<U9')

In [59]:
np.char.title(arr)

array(['Yashh', 'Pancharya'], dtype='<U9')

In [60]:
np.char.lower(arr)

array(['yashh', 'pancharya'], dtype='<U9')

In [61]:
#numpy - mathematical  function

In [62]:
arr2

array([[7, 8, 4, 1],
       [2, 6, 2, 8],
       [9, 5, 1, 9]])

In [63]:
np.sin(arr2)

array([[ 0.6569866 ,  0.98935825, -0.7568025 ,  0.84147098],
       [ 0.90929743, -0.2794155 ,  0.90929743,  0.98935825],
       [ 0.41211849, -0.95892427,  0.84147098,  0.41211849]])

In [64]:
np.cos(arr2)

array([[ 0.75390225, -0.14550003, -0.65364362,  0.54030231],
       [-0.41614684,  0.96017029, -0.41614684, -0.14550003],
       [-0.91113026,  0.28366219,  0.54030231, -0.91113026]])

In [65]:
np.tan(arr2)

array([[ 0.87144798, -6.79971146,  1.15782128,  1.55740772],
       [-2.18503986, -0.29100619, -2.18503986, -6.79971146],
       [-0.45231566, -3.38051501,  1.55740772, -0.45231566]])

In [66]:
np.tanh(arr2)

array([[0.99999834, 0.99999977, 0.9993293 , 0.76159416],
       [0.96402758, 0.99998771, 0.96402758, 0.99999977],
       [0.99999997, 0.9999092 , 0.76159416, 0.99999997]])

In [67]:
np.log10(arr2)

array([[0.84509804, 0.90308999, 0.60205999, 0.        ],
       [0.30103   , 0.77815125, 0.30103   , 0.90308999],
       [0.95424251, 0.69897   , 0.        , 0.95424251]])

In [68]:
np.exp(arr2)

array([[1.09663316e+03, 2.98095799e+03, 5.45981500e+01, 2.71828183e+00],
       [7.38905610e+00, 4.03428793e+02, 7.38905610e+00, 2.98095799e+03],
       [8.10308393e+03, 1.48413159e+02, 2.71828183e+00, 8.10308393e+03]])

In [70]:
np.sqrt(arr2)

array([[2.64575131, 2.82842712, 2.        , 1.        ],
       [1.41421356, 2.44948974, 1.41421356, 2.82842712],
       [3.        , 2.23606798, 1.        , 3.        ]])

In [71]:
np.power(arr2,3)

array([[343, 512,  64,   1],
       [  8, 216,   8, 512],
       [729, 125,   1, 729]])

In [72]:
np.mean(arr2)

5.166666666666667

In [74]:
np.median(arr2)

5.5

In [75]:
np.std(arr2)

2.9674156357941426

In [76]:
np.var(arr2)

8.805555555555555

In [77]:
np.min(arr2)

1

In [78]:
np.max(arr2)

9